# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Update README with latest commit id and push to repo
        run: |
          npm install -g mustache
          touch data.json
          echo "{\"COMMIT_ID\": \"0.1.2\"}" > data.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git status
          BRANCH_NAME=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
          echo "Running on branch: '$BRANCH_NAME'"
            if [[ "$BRANCH_NAME" = "main" ]]; then
              git pull --rebase origin main
              echo "COMMIT_ID=0.1.1"
              mustache data.json template.mustache > README_new.md
              awk -v id="$COMMIT_ID" '{gsub("commit-.*-blue", "commit-"id"-blue")}1' README.md > README_new.md
              mv README_new.md README.md
              if [ -n "$(git status --porcelain)" ]; then
                echo "There are changes in 'main'. Update README"
                git add README.md
                git commit -m "Update README with latest commit ID - $COMMIT_ID"
                git push -u origin main
              else
                echo "No local changes in 'main'. Nothing to update in the README."
              fi
            else
              echo "Not running in 'main'. No need to update README for branch: '$BRANCH_NAME'"
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
